fos_elastica:
    clients:
        default: { host: '%elastic_host%', port: 9200 }
    indexes:
        easyresto:
            finder: ~
            client: default
            types:
                restaurant:
                    properties:
                        id:
                            type: integer
                        status: ~
                        name: ~
                        city: ~
                        open: ~
                        location:
                            type: geo_point
                        categories:
                            type: "nested"
                            properties:
                                id :
                                    type : integer
                                name: ~
                    persistence:
                       driver: orm
                       model: AppBundle\Entity\Restaurant
                       finder: ~
                       provider: ~
                       repository: AppBundle\SearchRepository\RestaurantRepository
                tabMeal:
                    properties:
                        id:
                            type: integer
                        status: ~
                        name: ~
                        position:
                            type: integer
                        restaurant:
                            type: "nested"
                            properties:
                                id:
                                    type: integer
                                name: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\TabMeal
                        finder: ~
                        provider: ~
                        repository: AppBundle\SearchRepository\TabMealRepository
                categoryRestaurant:
                    properties:
                        id:
                            type: integer
                        status: ~
                        name: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\CategoryRestaurant
                        finder: ~
                        provider: ~
                        repository: AppBundle\SearchRepository\CategoryRestaurantRepository
                content:
                    properties:
                        id:
                            type: integer
                        status: ~
                        name: ~
                        type:
                            type: integer
                        price:
                            type: float
                        availability: ~
                        position:
                            type: integer
                        currentStock:
                            type: integer
                        restaurant:
                            type: "nested"
                            properties:
                                id:
                                    type: integer
                                name: ~
                        tab:
                            type: "nested"
                            properties:
                                id:
                                    type: integer
                                name: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Content
                        finder: ~
                        provider: ~
                        repository: AppBundle\SearchRepository\ContentRepository
                reservation:
                    properties:
                        id:
                            type: integer
                        state:
                            type: integer
                        nbParticipants:
                            type: integer
                        total:
                            type: float
                        date:
                          type: date
                        restaurant:
                            type: "nested"
                            properties:
                                id :
                                    type : integer
                                name: ~
                        user:
                            type: "nested"
                            properties:
                                id :
                                    type : integer
                                name: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Reservation
                        finder: ~
                        provider: ~
                        repository: AppBundle\SearchRepository\ReservationRepository