fos_elastica:
    clients:
        default: { host: '%elastic_host%', port: 9200 }
    indexes:
        easyresto:
            finder: ~
            client: default
            types:
                restaurant:
                    properties:
                        id:
                            type: integer
                        status: ~
                        name:
                          type: text
                        city: ~
                        open: ~
                        users:
                            type: "nested"
                            properties:
                              id:
                                type: integer
                        location:
                            type: geo_point
                        categories:
                            type: "nested"
                            properties:
                                id :
                                    type : integer
                                name: ~
                    persistence:
                       driver: orm
                       model: AppBundle\Entity\Restaurant
                       finder: ~
                       provider: ~
                       repository: AppBundle\SearchRepository\RestaurantRepository
                tabMeal:
                    properties:
                        id:
                            type: integer
                        status: ~
                        name: ~
                        position:
                            type: integer
                        restaurant:
                            type: "nested"
                            properties:
                                id:
                                    type: integer
                                name: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\TabMeal
                        finder: ~
                        provider: ~
                        repository: AppBundle\SearchRepository\TabMealRepository
                categoryRestaurant:
                    properties:
                        id:
                            type: integer
                        status: ~
                        name: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\CategoryRestaurant
                        finder: ~
                        provider: ~
                        repository: AppBundle\SearchRepository\CategoryRestaurantRepository
                ingredient:
                  properties:
                    id:
                      type: integer
                    status: ~
                    name: ~
                    stock:
                      type: integer
                  persistence:
                    driver: orm
                    model: AppBundle\Entity\Ingredient
                    finder: ~
                    provider: ~
                    repository: AppBundle\SearchRepository\IngredientRepository
                content:
                    properties:
                        id:
                            type: integer
                        status: ~
                        name: ~
                        type:
                            type: integer
                        price:
                            type: float
                        availability: ~
                        position:
                            type: integer
                        restaurant:
                            type: "nested"
                            properties:
                                id:
                                    type: integer
                                name: ~
                        tab:
                            type: "nested"
                            properties:
                                id:
                                    type: integer
                                name: ~
                    persistence:
                      driver: orm
                      model: AppBundle\Entity\Content
                      finder: ~
                      provider: ~
                      repository: AppBundle\SearchRepository\ContentRepository

                mealSet:
                  properties:
                    id:
                      type: integer
                    status: ~
                    name: ~
                    restaurant:
                      type: "nested"
                      properties:
                        id:
                          type: integer
                  persistence:
                    driver: orm
                    model: AppBundle\Entity\MealSet
                    finder: ~
                    provider: ~
                    repository: AppBundle\SearchRepository\MealSetRepository


                mealSetElement:
                    properties:
                      id:
                        type: integer
                      content:
                        type: "nested"
                        properties:
                          id:
                            type: integer
                      mealSet:
                        type: "nested"
                        properties:
                          id:
                            type: integer

                    persistence:
                      driver: orm
                      model: AppBundle\Entity\MealSetElement
                      finder: ~
                      provider: ~
                      repository: AppBundle\SearchRepository\MealSetElementRepository


                reservation:
                    properties:
                        id:
                            type: integer
                        state:
                            type: integer
                        nbParticipants:
                            type: integer
                        total:
                            type: float
                        date:
                          type: date
                        restaurant:
                            type: "nested"
                            properties:
                                id :
                                    type : integer
                                name: ~
                        user:
                            type: "nested"
                            properties:
                                id :
                                    type : integer
                                username: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Reservation
                        finder: ~
                        provider: ~
                        repository: AppBundle\SearchRepository\ReservationRepository


                reservationContent:
                    properties:
                        id:
                          type: integer
                        totalPrice:
                          type: float
                        quantity:
                          type: integer
                        content:
                          type: "nested"
                          properties:
                            id:
                              type: integer
                        reservation:
                          type: "nested"
                          properties:
                            id:
                              type: integer
                        seat:
                          type: "nested"
                          properties:
                            id:
                              type: integer

                    persistence:
                        driver: orm
                        model: AppBundle\Entity\ReservationContent
                        finder: ~
                        provider: ~
                        repository: AppBundle\SearchRepository\ReservationContentRepository
