AppBundle\Entity\User:
    exclusion_policy: none
    properties:
      status:
        exclude: true
      roles:
        exclude: true
      types:
        exclude: true
      civilities:
        exclude: true
      enabled:
        exclude: true
      salt:
        exclude: true
      password:
        exclude: true
      plainPassword:
        exclude: true
      birthDate:
        expose: true
        type: DateTime<'Y-m-d'>
      city:
        exclude_if: "object.getType() == 1"
      address:
        exclude_if: "object.getType() == 1"
      addressComplement:
        exclude_if: "object.getType() == 1"
      favorites:
        exclude_if: "object.getType() == 2"
