AppBundle\Entity\MealSetElement:
    exclusion_policy: none
    properties:
      restaurant:
        exclude: true
      status:
        exclude: true
      types:
        exclude: true
      mealSet:
        exclude: true