AppBundle\Entity\Content:
    exclusion_policy: none
    properties:
      restaurant:
        exclude: true
      status:
        exclude: true
      types:
        exclude: true
      availability:
        exclude: true
      price:
        exclude_if: "object.getType() == 2"
      description:
        exclude_if: "object.getType() == 2"
      ingredients:
        exclude_if: "object.getType() != 1"
      tab:
        exclude: true
      type:
        exclude: true
      position:
        exclude: true