AppBundle\Entity\User:
    exclusion_policy: none
    properties:
      status:
        exclude: true
      roles:
        exclude: true
      types:
        exclude: true
      civilities:
        exclude: true
      usernameCanonical:
        exclude: true
      emailCanonical:
        exclude: true
      enabled:
        exclude: true
      salt:
        exclude: true
      password:
        exclude: true
      plainPassword:
        exclude: true
      birthDate:
        expose: true
        type: DateTime<'Y-m-d'>